### ISSUE TITLE
error when using default fuzzing? 

### ISSUE THREAD

**Issue by stuartly** [avatartwo/ndss18_wycinwyc#1]
I try the sample, but it does not work.

```
stly@ubuntu:~/Documents/Kernel_Fuzzing/Tools/vagrant/experiments/scripts$ python wycinwyc_fuzzer.py -p
usage: wycinwyc_fuzzer.py [-h] [-m {0,1,2,3}] [-s SERIAL_DEVICE] [-p PORT]
                          [-t TIMEOUT] [-b BINARY] [-e ELF_FILE] [--callstack]
                          [--callframe] [--segment] [--format] [--heap_object]
                          [--stack_object] [-r] [-d DURATION] [--no-ykush]
                          [-c CORRUPTION_PROBABILITY] [-o OUTPUT_DIR] [-v]
```

```

python2 scripts/wycinwyc_fuzzer.py -d 3600 -t 1 -m 0 -c 0.0 
Traceback (most recent call last):
  File "scripts/wycinwyc_fuzzer.py", line 387, in <module>
    main(**kwargs)
  File "scripts/wycinwyc_fuzzer.py", line 326, in main
    fuzzing_session.fuzz()
  File "/usr/local/lib/python2.7/dist-packages/boofuzz/sessions.py", line 403, in fuzz
    self._main_fuzz_loop(self._iterate_protocol())
  File "/usr/local/lib/python2.7/dist-packages/boofuzz/sessions.py", line 470, in _main_fuzz_loop
    self._fuzz_current_case(*fuzz_args)
  File "/usr/local/lib/python2.7/dist-packages/boofuzz/sessions.py", line 939, in _fuzz_current_case
    target.open()
  File "/usr/local/lib/python2.7/dist-packages/boofuzz/sessions.py", line 73, in open
    self._target_connection.open()
  File "/usr/local/lib/python2.7/dist-packages/boofuzz/serial_connection.py", line 68, in open
    self._connection.open()
  File "/usr/local/lib/python2.7/dist-packages/boofuzz/serial_connection_low_level.py", line 41, in open
    self._device = serial.Serial(port=self.port, baudrate=self.baudrate)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
```

**Comment by mariusmue** [comment]
Huh, sorry for the delay, I somehow missed to be notified for the issue.

Anyhow. Do you have a Nucleo-board attached to your host-system and followed the instructions listed under hardware requirements in the Readme? The error is hinting that no serial port is exposed under /dev/ttyUSB0.

Regarding the example commandline arguments for the script, you can checkout the [run_experiments.py](https://github.com/avatartwo/ndss18_wycinwyc/blob/master/experiments/run_experiments.py)-file.

**Comment by louisjohn0416** [comment]
so if we just experiment the full-emulation mode, shall we still need a hardware connected to it ?
I do it in that way, but it seems that the openocd cannot work with socket connection to qemu emulator
with the tcp port 9998

**Comment by louisjohn0416** [comment]
so if we just experiment the full-emulation mode, shall we still need a hardware connected to it ?
I do it in that way, but it seems that the openocd cannot work with socket connection to qemu emulator
through the tcp port 9998

**Comment by mariusmue** [comment]
OpenOCD is just there to talk to the hardware; If you want to go for real full emulation, you'd need to remove this target completely.
However, at the moment, it is used to create an "initial snapshot" of the devices memory and register state, which gets then loaded into the Emulator. (https://github.com/avatartwo/ndss18_wycinwyc/blob/master/experiments/scripts/wycinwyc_avatar_helper.py#L192)

If you want to get rid of the hardware completely, you'd need to create this snapshot first and start from there, only using the PandaTarget.

**Comment by louisjohn0416** [comment]
Got it, But without hardware, i cannot creat this snapshot, isn't it ?
so would you please share this snapshot over this repo ?
also thank you for your reply

**Comment by mariusmue** [comment]
Added with 2591c2a18d08498cd7de26558ebbda9ab468f995 in experiments/dumps. Note that the dumped files have to be copied manually to the avatar output directory (/tmp/wycinwyc_fuzzing).

I will close this issue for now, but are happy to help in case of other problems.
