### ISSUE TITLE
Can I do the experiment without equipment

### ISSUE THREAD

**Issue by ZakiG** [avatartwo/ndss18_wycinwyc#2]
Hello, I haven't bought the required equipment at present, can I try to carry out the experiment through `PE/PM: Partial Emulation with Peripheral Modeling`. 
As described in the paper:
`The firmware is emulated and peripheral interaction is handled by mimicking peripherals behavior with ded- icated scripts inside Avatar, which allows to conduct experiments without having a physical device present.`
If so , how can I do it . Thanks

**Comment by mariusmue** [comment]
Hi  ZakiG.

Yes, this should be possible - I added the neccessary files with 2591c2a18d08498cd7de26558ebbda9ab468f995.

After setting up the experiments, (or checking out the vagrant image), it's just a matter of invoking [`experiments/scripts/wycinwyc_fuzzer.py`](https://github.com/avatartwo/ndss18_wycinwyc/blob/master/experiments/scripts/wycinwyc_fuzzer.py) with the right mode, i.e., mode 2 and 3.

Let me know how it goes!
Cheers,
Marius

**Comment by ZakiG** [comment]
Hi, Mariusmue
I conducted the experiment through `vagrant image(avatar2/ndss18_wycinwyc)`. Since there was no equipment, I tried to use mode 2 and mod3, just `partial rehosted with python peripherals` and `fully rehosted`. However, I got those connection errors:

python2 scripts/wycinwyc_fuzzer.py -d 3600 -t 1 -m 3 -c 0.10 --heap_object --segment --format --stack_object
Traceback (most recent call last):
  File "scripts/wycinwyc_fuzzer.py", line 387, in <module>
    main(**kwargs)
  File "scripts/wycinwyc_fuzzer.py", line 306, in main
    target.procmon.restart_target()
  File "scripts/wycinwyc_fuzzer.py", line 132, in restart_target
    return False if not self.start_target() else True
  File "scripts/wycinwyc_fuzzer.py", line 121, in start_target
    self.record, self.port)
  File "/home/vagrant/experiments/scripts/wycinwyc_avatar_helper.py", line 193, in start_avatar
    nucleo.init()
  File "/usr/local/lib/python2.7/dist-packages/avatar2/targets/openocd_target.py", line 48, in init
    if openocd.connect() and gdb.remote_connect(port=self.gdb_port):
  File "/usr/local/lib/python2.7/dist-packages/avatar2/protocols/openocd.py", line 72, in connect
    self._telnet = telnetlib.Telnet('127.0.0.1', self._telnet_port)
  File "/usr/lib/python2.7/telnetlib.py", line 211, in __init__
    self.open(host, port, timeout)
  File "/usr/lib/python2.7/telnetlib.py", line 227, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

With a simple debug, those errors are in the `nucleo.init()`.  If I don't have the equipment, can I continue the experiment. 
I'm very sorry if I disturb you :(
Best,
Zaki

**Comment by mariusmue** [comment]
Hi,
First of all, don't worry about disturbing me, I'm happy to give support and are unhappy that the setup is so tedious.

That being said, did you make sure that the folder [experiments/dumps](https://github.com/avatartwo/ndss18_wycinwyc/tree/master/experiments/dumps) is present and contains both files as here in the repository? If so, those files have to be copied to the specified avatar-output repository (per default, this is `/tmp/fuzzing`).

The reason for this is, that the script tries to create this files if not present - and for the generation, the hardware is needed. Additionally, it may be that the vagrant image does not has the files yet, as it is an old version.

**Comment by ZakiG** [comment]
Many thanks! 
I will finish the experiment. The work of you and your team is remarkable and practical.
Best,
Zaki
